var events1 = [
  {
    "prompt": "Gromyulox knocks over the city's largest bank, pinning Brutadon beneath its financial hulk. Brutadon sobs and sniffles in shame!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon takes advantage of his ground-level position and bites Gromyulox in the ankle! Take that, Gromyulox!",
    "s1": 1,
    "t2": "Brutadon flexes his giant muscles, and the bank shatters into a million pieces! Gromyulox gasps in terror!",
    "s2": 1,
    "t3": "Brutadon is heartened by your encouragement-- but encouragement can't lift banks! Gromyulox stomps on his poor face!",
    "s3": 0,
    "t4": "Brutadon growls in confusion, but he obediently lies under the bank wreckage. Gromyulox stomps all over his face! Ouch!",
    "s4": 0,
    "t5": "Brutadon is so scared! He wails and roars under the bank while Gromyulox roasts him with radioactive fire!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the sound of all these screaming financiers!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox punches Brutadon so hard, one of Brutadon's extra eyeballs falls out on the ground!",
    "wreck": 1,
    "pump": 1,
    "got": 2,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon stomps on his own eyeball! He uses his remaining ones to stare Gromyulox down! It's an incredible power move, and Gromyulox is extremely intimidated!",
    "s1": 1,
    "t2": "Brutadon grits his teeth and pushes through the pain! Your encouragement is all he needs!",
    "s2": 1,
    "t3": "Brutadon recoils, and Gromyulox closes in for a second punch. KABLAMMO! He knocks out one of Brutadon's extra tongues!",
    "s3": 0,
    "t4": "Brutadon can't hear you over his howls of pain!",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon's cell phone rings in the middle of the fight! You can tell from his anxious growls that it's his tax preparer! This call is too important for him to skip!",
    "wreck": 1,
    "pump": 1,
    "got": 2,
    "hold": 2,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon roars into his cell phone, shattering it into a million pieces! Oh no! That's going to affect his maximum return!",
    "s1": 0,
    "t2": "Brutadon goes on the retreat, successfully sidestepping all of Gromyulox's punches! He successfully resolves the confusion about his freelance income mid-fight, which will help his tax preparer maximize his returns. Wow!",
    "s2": 1,
    "t3": "Brutadon is too confused to solve this problem without your help! He hurls his cell phone into the sea. Oh no! That's going to affect his maximum return!",
    "s3": "",
    "t4": "Brutadon can't hear you over the voice of his tax preparer!",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Suddenly, you see the expression on Brutadon's face change. You can tell that he's experiencing a bout of imposter syndrome!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon doesn't feel confident enough to wreck anyone today! He cowers in shame and Gromyulox punches him in the gut!",
    "s1": 0,
    "t2": "Brutadon halfheartedly tries to pump himself up, but he's feeling too imposterish to fully flex his muscles to their full potential. Oh no!",
    "s2": 0,
    "t3": "You are a true friend. When Brutadon feels cherished by a true friend, he can achieve anything. He shakes himself free from the metaphorical tentacles of imposter syndrome, and faces the actual tentacles of Gromyulox's horrible monster body!",
    "s3": 1,
    "t4": "Brutadon's already holding back. He's been holding himself back in fear this whole time. When he hears your voice, a single steaming tear rolls down his scaly cheek, and he knows that he's an imposter, just like he always feared.",
    "s4": 0,
    "t5": "Brutadon waits and waits for emotional support from you during this time of need, but it never comes. A single steaming tear rolls down his scaly cheek, and he knows that he's an imposter, just like he always feared.",
    "s5": 0,
    "t6": "Brutadon can't hear you over the sound of his churning, imposter thoughts.",
    "s6": ""
  },
  {
    "prompt": "Gromyulox trips on a firetruck, opening himself up for a strike!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon ducks low and swings hard, smashing Gromyulox in the ribs! Success! Gromyulox roars in all seven of his cosmic pain languages!",
    "s1": 1,
    "t2": "Brutadon flexes impressively! It's cool, but unfortunately it has no effect on Gromyulox's health or wellbeing!",
    "s2": 0,
    "t3": "Brutadon sees the opening, but he doesn't strike! Gromyulox uses this opportunity to regain his monstrous strength. Every inch of his hide starts to ooze radioactive nitro-sweat. Now he's even more dangerous!",
    "s3": 0,
    "t4": "Without your guidance, Brutadon just does what he's most comfortable with: helpless flailing and stomping! None of his hits connectl. Gromyulox cackles in glee!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the sound of Gromyulox's shrieking!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon and Gromyulox stumble into the middle of a wedding! Guests run screaming in every direction!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon crushes hundreds of wedding guests with his enormous toes! Dresses and tuxedoes wet with blood cling to the soles of his feet!",
    "s1": 0,
    "t2": "Brutadon flexes and expands his neck sacs and howls at the sky! Every glass in the reception shatters, but at least nobody got hurt!",
    "s2": 1,
    "t3": "Brutadon's eyes light up. You got this, Brutadon? Does that mean this wedding cake is for him? He reaches down, scoops up the entire buffet, and swallows it whole-- along with half the wedding party! Oh no!",
    "s3": 0,
    "t4": "Brutadon balances on one foot as helpless wedding guests scramble to get out of the way. Gracefully, he avoids hurting even one person!",
    "s4": 1,
    "t5": "Brutadon panics and freaks out and just crushes the entire wedding! Poor guy! He probably could have used some guidance there!",
    "s5": 0,
    "t6": "Brutadon can't year you over the sound of the wedding band!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox bites down hard on Brutadon's bicep! Brutadon wails in pain!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon tries to wreck him, but he can't! His punching arm is trapped in Gromyulox's diamond teeth! His sizzling hot blood splatters everywhere!",
    "s1": 0,
    "t2": "Brutadon flexes so hard, he shatters every one of Gromyulox's diamond teeth! Tooth shards glitter in the sun! Wow!",
    "s2": 1,
    "t3": "Brutadon is terrified. He doesn't got this! Gromyulox has got this, if by \"this\" we mean \"Brutadon's arm\"! Gromyulox uses this opportunity to punch Brutadon in the neck!",
    "s3": 0,
    "t4": "Brutadon follows your orders, and just lets Gromyulox bite the hell out of his poor arm! Ouch! Brutadon's steaming blood flies sizzling through the sky!",
    "s4": 0,
    "t5": "Brutadon doesn't know what to do! He just stands there and lets Gromyulox chew all over his poor arm! Ouch! He howls miserably at the sky!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the sound of his muscles getting all chewed up!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox and Brutadon trip over a bridge and fall into the river with a splash. Gromyulox tries to push Brutadon's head underwater!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon obeys your orders and wrecks the bridge. It falls on him and trap him in the river! He inhales fifty million gallons of water, extinguishing three of his five radioactive lungs! Oh no!",
    "s1": 0,
    "t2": "Brutadon sucks up a mouthful of water and spits it at Gromyulox! it's boiling hot! Gromyulox's outer skin melts and sluffs off in sheets of sizzling meat! The crowd on the riverbank cheers!",
    "s2": 1,
    "t3": "Brutadon steels his resolve and holds his breath underwater! Gromyulox thinks he has won. But then Brutadon rears up out of the river and socks Gromyulox in the jaw! Good one Brutadon!",
    "s3": 1,
    "t4": "Brutadon freaks out and struggles! But the more he struggles, the more water he swallows! He inhales fifty million gallons of river, extinguishing three of his five radioactive lungs! Oh no!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the water churning in his ears!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon's spirit is burdened. It has been a difficult day, and you can see it on Brutadon's craggy face. He sits down on a nearby apartment building, despondent.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon had forgotten the intrinsic joy of his colossal existence. He, can wreck them. He, will wreck them. He punches a car-sized hole in the apartment building. He is filled with determination.",
    "s1": 1,
    "t2": "Brutadon does not feel like pumping it up. Brutadon does not feel that you empathize with his existential woe.",
    "s2": 0,
    "t3": "Brutadon has held back his feelings for so long that he feels like his heart is about to pop like a bubble.",
    "s3": 0,
    "t4": "You ignore Brutadon, just like he has been ignoring his innermost turmoil for his entire life.",
    "s4": 0,
    "t5": "Brutadon growls in sad confusion. He can't tell what you said.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox roars and nearby windows shatter. Although Brutadon knows that he is a bad customer, he is afraid that Gromyulox is even badder.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon roars right back at Gromyulox. His cheeks quiver with sonic fury. Gromyulox recoils from the noise, like a coward. Brutadon has won this round.",
    "s1": 1,
    "t2": "Brutadon flexes his muscles. Although he knows that they are large, he cannot help but look over at Gromyulox's seven massive biceps, which are extremely intimidating.",
    "s2": 0,
    "t3": "In the face of doubt, Brutadon holds fast. He knows that he is very large and very strong. This is not a David and Goliath situation. It is a Goliath and Goliath situation. Brutadon roars wtih confidence.",
    "s3": 1,
    "t4": "Without your encouragement, Brutadon's doubt festers like a wound in his brain. A wound that is becoming infected. Brutadon flinches. Gromyulon has won this round of psychic battle.",
    "s4": 0,
    "t5": "Brutadon doesn't know what you're saying. He continues to feel unsure about his badditude.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox swings his giant fist. Brutadon ducks to the side like a hefty, thumping ninja. He looks over at you, face plastered with a reptilian smile.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon simultaniously jabs from the left, jabs from the right, and uses his middle arm to uppercut Gromyulox's largest chin. Gromyulox gets wrecked. He gets wrecked real good.",
    "s1": 1,
    "t2": "Brutadon pumps up his muscles. Gromyulox is surprised, perhaps even slightly cowed, by the combination of Brutadon's dexterity and muscularity.",
    "s2": 1,
    "t3": "Brutadon holds back and he misses his opening. His lizardish smile turns to a lizardish frown when Gromyulox's follow up combination strikes him right in his topmost liver.",
    "s3": 0,
    "t4": "Brutadon was waiting for your encouragement, but he did not get it. Gromyulox takes advantage of Brutadon's hesitation with a spinning triple kick. Brutadon crashes to the ground, killing one hapless human and causing several others to suffer from years of P T S D.",
    "s4": 0,
    "t5": "Brutadon did not understand you. He continues to grin, waiting for you to clarify your instructions.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon showers Gromyulox with a barrage of flying hammer punches, but Gromyulox blocks all of them. Brutadon grunts in frustration. He is not sure if he's got this.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 1,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon continues to hammer punch, even though Gromyulox has clearly mastered the art of blocking hammer punches. Brutadon tires himself out. The spikes on the bottom of Gromyulox's feet emerge from their gooey pouches, and Gromyulox stomps on Brutadon's feet.",
    "s1": 0,
    "t2": "Hammer punches clearly are not working. Brutadon shifts to a different tactic -- the tried and true flexing that he has practiced during your training sessions for hundreds of hours. Unfortunately, flexing is not the correct move in this situation, and Brutadon gets 3 of his 700 teeth knocked out.",
    "s2": 0,
    "t3": "Yes. He, does, got this. He switches from hammer punches to asteroid elbows, and one of them lands on Gromyulox's fleshy left neck, causing the concrete below your feet to crackle like a space blanket.",
    "s3": 1,
    "t4": "Without your input, Brutadon continues to hammer punch, even though Gromyulox has clearly mastered the art of blocking hammer punches. Brutadon tires himself out. The spikes on the bottom of Gromyulox's feet emerge from their gooey pouches, and Gromyulox stomps on Brutadon's feet.",
    "s4": 0,
    "t5": "Brutadon doesn't understand you, perhaps because the thunder of the hammer punches is pretty loud.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "You notice that standing next to Brutadon's left foot, a brave spectator is trying to take a selfie with Brutadon.",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon smooshes that spectator with a casual stomp. This will be a P R disaster.",
    "s1": 0,
    "t2": "Brutadon strikes a heroic pose for the spectator. You know that this will bolster Brutaon's viral presence on social media.",
    "s2": 1,
    "t3": "Brutadon avoids squashing the spectator and maintains his focus on the fight with Gromyulox. The selfie that the spectator took will later go viral and be featured on Good Morning America.",
    "s3": 1,
    "t4": "Brutadon does not notice the spectator and he accidentally crushes half of the spectator's body under his right toe. The spectator still manages to take a selfie, but the selfie is the stuff of nightmares. This will be a P R disaster.",
    "s4": 0,
    "t5": "Brutadon knows that you are trying to say something, but he didn't hear you very well. The situation continues to be very dangerous for the spectator.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon spins like a tornado and his spikey tail whistles through the air. It is a truly terrifying sight. Gromyulox cannot get away in time. Globules of blood, the color of Merlot, slop onto the concrete.",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Oh, he wrecked it. Damn straight did he wreck it. Your enthusiasum is contagious. Brutadon's emotion bulb turns a pleasing shade of orange and you know this means that he feels like he can take on the world.",
    "s1": 1,
    "t2": "Damn straight. Your enthusiasum is contagious. Brutadon's emotion bulb turns a pleasing shade of orange and you know this means that he feels like he can take on the world.",
    "s2": 1,
    "t3": "Brutadon does not maintain his elevated hype level and he exits his state of flow. Sometimes, if you do not celebrate your victories, they do not sink in.",
    "s3": 0,
    "t4": "Brutadon didn't understand you. You should probably encourage Brutadon because that was pretty bad ass.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon steps on a statue of a Civil War general, and the statue's stone sword sticks in his toe like a splinter! Ouch!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon roars in anger and smashes the statue into a million tiny pieces! It makes him feel a lot better! He pushes through the pain!",
    "s1": 1,
    "t2": "Brutadon flexes his toe muscles so hard, that the splinter shoots out of his toe like a missile, and hits Gromyulox dead in the eyeball! Hell yeah!",
    "s2": 1,
    "t3": "Brutadon grits his teeth and pushes through the pain! Splinters mean nothing! Toes mean nothing! Toes are like dirt! Brutadon roars at the sky and slaps Gromyulox across the face!",
    "s3": 1,
    "t4": "Brutadon favors his injured foot. Gromyulox notices this weakness! He closes in and lands a flurry of bone, destroying, punches, on Brutadon's vulnerable side!",
    "s4": 0,
    "t5": "Brutadon tries to muddle through the pain, but Gromyulox notices his injury! He stomps down, hard, on Brutadon's toe. Brutadon's scream of pain shatters all the windows on the west side of town!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the sound of his own sniffles.",
    "s6": ""
  },
  {
    "prompt": "Brutadon smells a delicious panini, cooking in a nearby restaurant! Oh no! It's distracting him!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon smashes the restaurant! All the people and objects inside it, are crushed and mixed together into a paste! They will have to be buried with their paninis!",
    "s1": 0,
    "t2": "Brutadon flexes so hard, that his muscles release a cloud of battle pheromones! This scent blocks out the alluring smell of the paninis. Brutadon is saved!",
    "s2": 1,
    "t3": "Brutadon takes your advice, and goes to find these delicious paninis. Gromyulox uses this opportunity to stab Brutadon in the butt with one of his venom tusks! Brutadon roars in agony!",
    "s3": 0,
    "t4": "Brutadon successfully restrains himself! Now is the time for deadly battle, not for paninis!",
    "s4": 1,
    "t5": "Without anyone to tell him it's a bad idea, Brutadon goes to find these delicious paninis. Gromyulox uses this opportunity to stab Brutadon in the butt with one of his venom tusks! Brutadon roars in agony!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the chorus of  his subconscious as it demands paninis.",
    "s6": ""
  },
  {
    "prompt": "Gromyulox rips up a railroad and cracks it through the air like a whip. Oh no! It's electrified, and very dangerous!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon rushes forward. Bad idea! He gets electrical burns, all over his precious neon hide!",
    "s1": 0,
    "t2": "Brutadon starts showing off all his muscles. But while he's grunting, and flexing, Gromyulox slashes him with the electrical railroad. YAOWCH! That hurts!",
    "s2": 0,
    "t3": "Brutadon gets out of range of Gromyulox's electrical railroad whip. Good idea! Gromyulox just ends up tangling himself in his own weapon, and giving himself electrical burns, on all twelve of his thighs!",
    "s3": 1,
    "t4": "Brutadon isn't sure what to do, so he just flops down on the ground, and cries, while Gromyulox hits him with the electrical railroad. YAOWCH!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the sound of the crackling electrical railroad whip.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox grabs a cell phone tower, and hurls it at Brutadon like a spear!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon smashes the cellphone tower out of the air, with one swipe of his gigantic claw! It sticks in a nearby hill like an arrow. Awesome! People all over the east side of town gasp in amazement!",
    "s1": 1,
    "t2": "Brutadon flexes so hard that his outer scales transform suddenly into diamond! The cellphone tower bounces harmlessly off his impenetrable hide!",
    "s2": 1,
    "t3": "Brutadon steels his nerves. At the last moment, he expertly sidesteps the cellphone tower! It buries itself in the ground exactly where he was standing, and explodes in a giant fireball for some reason! Close call!",
    "s3": 1,
    "t4": "Brutadon retreats out of the range of Gromyulox's puny throw. Hah! What a bad thrower! Gromyulox must not have a cool friend to play football with him in the park, like Brutadon does.",
    "s4": 1,
    "t5": "Brutadon isn't sure what to do, so he hesitates. Wrong decision! The cellphone tower spears him in the side! Sizzling blood globs spray everywhere!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the sound of the deadly cell phone tower whistling through the air!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox grabs a school bus full of children and swings it at Brutadon like a club!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 1,
    "huh": 5,
    "t1": "Brutadon rushes forward, and the bus connects hard with the side of his head! Splattered, schoolchildren, stream down his face in chunks! Brutadon is dazed by both the pain and the horror!",
    "s1": 0,
    "t2": "Brutadon stands aside and flexes all of his limbs simultaneously. Inside the schoolbus, the children catch a glimpse of his glorious muscles, and the terror in their hearts is calmed. As Gromyulox hurls them into the river, they die in peace. Good job Brutadon!",
    "s2": 1,
    "t3": "Brutadon deftly catches the schoolbus and rips it out of Gromyulox's claws. He sets it down carefully on the road. Most of the children survive! Good job Brutadon!",
    "s3": 1,
    "t4": "Brutadon jumps back, and dodges the swing. Inside the schoolbus, the children catch a glimpse of his glorious muscles rippling past the windows, and the terror in their hearts is calmed. As Gromyulox hurls them into the river, they die in peace. Good job Brutadon!",
    "s4": 1,
    "t5": "Brutadon can't hear you over the sound of the screaming schoolchildren!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox hipchecks Brutadon into the largest skyscraper downtown and bodyslams him into the park! Brutadon is dazed and half-buried by rubble!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon grabs Gromyulox by the ankle and hurls him into the duck pond! Gromyulox wails in horror as enormous hives sprout all over his three butts. His kind is allergic to waterfowl!",
    "s1": 1,
    "t2": "Brutadon flexes so hard that the lumps of rubble and debris bounce off his hide and fly through the air like missiles! Every window nearby is shattered, and Gromyulox staggers backward across midtown! Nice!",
    "s2": 1,
    "t3": "Brutadon tries to smile, while Gromyulox pummels him in the face. Ouch! Ouch! Ouch! Smiling doesn't help!",
    "s3": 0,
    "t4": "Brutadon lies flat on the ground in the park while Gromyulox sits on his back and bites his neck. This is not a winning strategy!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the sound of the ducks freaking out in the duck pond.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon stands over Gromyulox, punching him again and again in the face. But an airplane is coming in for a landing at the city airport, and Brutadon's head is right in the way!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 2,
    "huh": 5,
    "t1": "At exactly the right moment, Brutadon bends over to bite Gromyulox in the neck, and the airplane just misses his shoulders by a few feet! Wow! Close call! Everyone in the airplane is probably pooping their pants!",
    "s1": 1,
    "t2": "The plane smashes into the back of Brutadon's head, killing hundreds and burning Brutadon terribly. But at least his fine body was flexing while it happened!",
    "s2": 0,
    "t3": "Brutadon misinterprets your cheer as encouragement to keep punching! The plane smashes into the back of his head, knocking him flat! YAOWCH!",
    "s3": 0,
    "t4": "At the last second, Brutadon steps back, and the plane whizzes right through where he was standing! Close call! Everyone in the airplane is probably pooping their pants!",
    "s4": 1,
    "t5": "Brutadon can't hear you over the sound of his fists hitting Gromyulox's body!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon and Gromyulox stumble into the middle of an illegal street race! High-powered customized cars, covered in knives and driven by howling wasteland rabble, zoom straight at their toes!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon destroys the zooming cars with a single stomp-- but huge knives and bits of twisted rebar stick in his foot! YAOWCH!! Skinhead warboy street racers are smeared all over his toes!",
    "s1": 0,
    "t2": "Brutadon roars at the cars! The force of his breath is strong enough to send them skidding back down the road! The street racers crap their pants, bail out, and run away. Nice!",
    "s2": 1,
    "t3": "Brutadon jumps back out of the cars' way. They plow into Gromyulox's ankles, and he bellows in agony! Nice!",
    "s3": 1,
    "t4": "The cars smash into Brutadon's ankles! Wasteland knives, and twisted bits of re-bar, and splinters of car metal stab him! YAOWCH!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the sound of the car engines!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "It is beginning to rain. You can tell from Brutadon's timid growl that he is remembering that one time during training that he slipped in the rain and sprained his ankle.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon charges at Gromyulox, but he once again slips in the rain. That's not good. Gromyulox takes the opening. He body slams Brutadon. Ouch town.",
    "s1": 0,
    "t2": "While pumping it up, Brutadon remembers how nice you were during his recovery period from his sprained ankle. You brought him his favorite soup every day. He knows that you've got his back, and that means all the world.",
    "s2": 1,
    "t3": "As he sees you cheering him on, Brutadon remembers how nice you were during his recovery period from his sprained ankle. You brought him his favorite soup every day. He knows that you've got his back, and that means all the world.",
    "s3": 1,
    "t4": "Brutadon stews in his bad memory of the rain. In his mind, the rain is his enemy. This makes him forget about his real enemy, Gromyulox. Gromyulox kicks him in his shins and it hurts a bunch.",
    "s4": 0,
    "t5": "Brutadon can't hear you. The rain is getting pretty loud. Splish splash.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Suddenly, huge fleshy wings, drop from Gromyulox's forearms. Oh no. You didn't know that Gromyulox had wings. You haven't trained for this. Gromyulox must have hidden his wings for all of this time, waiting for the perfect moment to unfurl them.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon punts a car and it flies through the air with uncanny accuracy. It tears right through Gromyulox's secret wings, rendering them flappy and unflightworthy. Nice one, Brutadon!",
    "s1": 1,
    "t2": "Brutadon flexes, trying to see if there is some hidden muscle that will reveal his own hidden wings. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "s2": 0,
    "t3": "Brutadon is dumbfounded by Gromyulox's secret wings. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "s3": 0,
    "t4": "Brutadon is dumbfounded by Gromyulox's secret wings, just like you are, apparently. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "s4": 0,
    "t5": "Brutadon didn't understand you. He is becoming increasingly worried at the sight of Gromyulox's mighty wings.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox crouches down to the ground. His body starts to get redder and redder. It seems like he is charging up some sort of super move.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon runs at Gromyulox, knocking him over before he can finish charging his super move. Gromyulox is dazed. Brutadon seizes his opening and stomps on Gromyulox with the force of ten thousand dump trucks. Damn, son.",
    "s1": 1,
    "t2": "Brutadon tries to charge up his own super move, but it is too late! A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "s2": 0,
    "t3": "Unfortunately, Brutadon don't got this. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "s3": 0,
    "t4": "Brutadon holds back, but this only allows Gromyulox to finish charging his super move. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "s4": 0,
    "t5": "While Brutadon is waiting for you to say something, Gromyulox finishes charging his super move. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "s5": 0,
    "t6": "Brutadon doesn't understand what you're saying. You should probably clarify soon, because Gromyulox is almost the shade of a tomato.",
    "s6": ""
  },
  {
    "prompt": "Brutadon growls, and you can tell that he has just remembered that he has to go to the post office. Going to the post office is a real chore, and it could have been avoided if Brutadon had signed up for stamps dot com. With stamps dot com you can buy and print real U S postage from the comfort of your own home. Stamps dot com makes sending packages easy. Check out stamps dot com for a no risk trial and a free postage offer! All you need to do is go to stamps dot com, click on the microphone on the top of the page, and enter, Brutadon. Why wait in long post office lines? Try stamps dot com today.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon wrecks his trips to the post office by going to stamps dot com, clicking on the microphone on the top of the page, and entering, Brutadon. Nice job, Brutadon!",
    "s1": 1,
    "t2": "Brutadon is pumped up to end his trips to the post office, which are the worst part of his week. He celebrates by going to stamps dot com, clicking on the microphone on the top of the page, and entering, Brutadon. Nice job, Brutadon!",
    "s2": 1,
    "t3": "Brutadon knows what he has to do. He goes to stamps dot com, clicks on the microphone on the top of the page, and enters, Brutadon. Nice job, Brutadon!",
    "s3": 1,
    "t4": "Although Brutadon intends to sign up for stamps dot com, he does not act now. Instead, he makes a trip to the post office and has to wait in a long line. Next time, Brutadon should go to stamps dot com, click on the microphone on the top of the page, and enter, Brutadon.",
    "s4": 0,
    "t5": "Brutadon didn't understand that. The post office lines sure are looking long.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon opens his mouth to breathe poison gas at Gromyulox. But a cloud of Canada Geese fly straight down his throat! Oh no! He can't breathe!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon belches fire, roasting all the geese! He swallows their crispy little bodies, and they fuel his fight energy! Get wrecked, geese!",
    "s1": 1,
    "t2": "Brutadon tries to flex, but he can't breathe! He coughs up mangled goose parts while Gronyulox punches him over and over in the neck! Ouch!",
    "s2": 0,
    "t3": "Brutadon just sits there and lets himself suffocate on a throatful of geese. Meanwhile, Gromyulox hits him over and over again, until he wobbles back and forth like a gym punching dummy. Good strategy! I mean, not a good strategy. This is sarcastic.",
    "s3": 0,
    "t4": "Brutadon can't hear you over the sound of the geese cawing in his throat.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon stumbles into a playground! Children run screaming everywhere!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon doesn't want to, but he takes your advice and eats all the children. He belches guiltily.",
    "s1": 0,
    "t2": "Brutadon flexes for the crowd. The children are reassured by his gentle strength. They cheer!",
    "s2": 1,
    "t3": "You've assured Brutadon that these children pose him no threat. He's relieved!",
    "s3": 1,
    "t4": "Brutadon successfully avoids murdering any of the puny fleeing children with his giant feet. Good job, Brutadon.",
    "s4": 1,
    "t5": "Without your guidance, Brutadon falls to the ground in confusion, crushing several children!",
    "s5": 0,
    "t6": "Brutadon can't understand you! He balances on one foot as children scurry like ants beneath him!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox charges at Brutadon with his shoulder needles set to full bristle!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon lifts his fists to wreck Gromyulox, but he cannot withstand the force of Gromyulox's mighty charge! His fists are punctured with poisonous quills. The poison causes a wicked headache, and the needles hurt a bunch.",
    "s1": 0,
    "t2": "Brutadon pumps up his inflatable shield pouch, but it is a bad defense against a needled attack. The shield pouch is punctured in 30 places, rendering it flaccid and useless!",
    "s2": 0,
    "t3": "Brutadon steels himself against Gromyulox's mighty charge. He waits for his moment, and then he adroitly dodges to the side! Gromyulox collides into a power plant and he is filled with 95,000 volts of electricity! He stumbles to his feet, smoking and concussed.",
    "s3": 1,
    "t4": "Brutadon does nothing, and Gromyulox collides with him, filling his body with poisonus quills! The poison afflict Brutadon a wicked headache and the needles cause him tremendous pain.",
    "s4": 0,
    "t5": "This is an urgent problem and Brutadon doesn't have time for your incoherent mumblings!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon suddenly freezes. Oh no. It's happened again. He's forgotten how to punch things!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Your voice stirrs something deep inside Brutadon. He remembers: punching is about wrecking things. Punching is about destruction! He leaps on Gromyulox with renewed vigor and expresses the true platonic ideal of the punch!",
    "s1": 1,
    "t2": "Brutadon raises his fist and makes a timid pumping motion. Is this it? Is this a punch? While he's still wondering, Gromyulox decks him in the jaw. Oh, that's it. That's a punch.",
    "s2": 0,
    "t3": "Brutadon just stands there, waving his arms around, hoping that maybe he is punching. While he's still wondering, Gromyulox decks him in the jaw. Oh, that's it. That's a punch.",
    "s3": 0,
    "t4": "Brutadon can't hear you over the sound of his confused and terrified punch thoughts.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "In the midst of furious battle, Brutadon begins to execute an extremely difficult and complex combination that he has practiced over 2000 times. You sense that this time, Brutadon is in the zone, and maybe you shouldn't distract him.",
    "wreck": 1,
    "pump": 1,
    "got": 1,
    "hold": 1,
    "none": 2,
    "huh": 3,
    "t1": "Your cries of support, although well intentioned, shatter Brutadon's focus. He whiffs his seventh middle backpunch and tumbles mightily to the ground.",
    "s1": 0,
    "t2": "You silently punch the air in time with Brutadon's complex combination, and your heart swells with pride as his final triple suplex lands perfectly. Great job, Brutadon!",
    "s2": 1,
    "t3": "What was that? Were you saying something distracting to Brutadon?",
    "s3": "",
    "t4": "",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "An elderly lady approaches Brutadon. She says to him, sweetie, you look like you are tired from all of this fighting, would you like some tea?",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "In what the newspapers would later describe as a gross abuse of power, Brutadon smashes the kind old lady and her teacups underfoot. You can tell from Brutadon's quiet growl that he did not want to smash the old lady, but he trusted you, and now he regrets it.",
    "s1": 0,
    "t2": "Not only would Brutadon like some tea, he would like for his tea to be pumped up with lots of extra sugar. He enjoys his refreshing and de-stressing beverage very much, and he thanks the old lady for her kindness.",
    "s2": 1,
    "t3": "Brutadon would have liked some tea, but he politely declines the old lady's offer, instead returning to the battle at hand. Before long, he wishes that he had accepted the tea, because he becomes very thirsty.",
    "s3": 0,
    "t4": "Brutadon accept's the old lady's kind offer, and he makes extra care to hold on to his tea, so as not to spill it and burn himself. He enjoys his refreshing and de-stressing beverage very much, and he thanks the old lady for her kindness.",
    "s4": 1,
    "t5": "Even though your input would have been reassuring, Brutadon is pretty sure that he can figure this one out on his own. He accept's the old lady's kind offer with a thankful growl. He enjoys his refreshing and de-stressing beverage very much, and he thanks the old lady for her kindness.",
    "s5": 1,
    "t6": "Brutadon didn't quite catch that.",
    "s6": ""
  },
  {
    "prompt": "Brutadon suddenly becomes entangled in a cloud of Amazon delivery drones. Oh no! Boxes of toilet paper and stacks of Shrek DVDs cascade down his scaly face!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon crushes countless drones and Shrek dvds in his jaws! Silver fragments of the classic irreverent family-friendly fairytale rain down over the city and sparkle between his teeth! Gromyulox is intimidated!",
    "s1": 1,
    "t2": "Brutadon flexes hard! Unfortunately, this does nothing to the pestering, irksome cloud of Amazon delivery drones!",
    "s2": 0,
    "t3": "Brutadon mistakes your cheer for a command to collect all of the falling Amazon merchandise! As Brutadon scrambles to catch Shrek DVDs before they hit the ground, Gromyulox sinks his teeth into Brutadon's neck! Your friend has been foiled by Shrek!",
    "s3": 0,
    "t4": "Brutadon tries to dodge the delivery drones, but there's too many of them! He flails around helplessly in the cloud of Amazon merchandise while Gromyulox punches him in the gut!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the sound of clattering DVD cases!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Perhaps coincidentally, and certainly unfortunately for the pilot, an attack helicopter is flying by overhead. Gromyulox performs an astonishing bicycle kick and suddenly the whirling blades are flying stright towards Brutadon!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon attempts to punch the metal meteor, but the spinning blades rip his hand to shreds, rendering his fourth arm useless. A tangled mess of hand flesh dangles from his wrist.",
    "s1": 0,
    "t2": "Brutadon pumps it up, trying to brace himself against the metal meteor. He flexes his muscles so hard that the attack helicopter riccochets off of his flesh. It's unreal. Gromyulox is dumbstruck.",
    "s2": 1,
    "t3": "Brutadon attempts to catch the metal meteor, but the spinning blades rip his hand to shreds, rendering his fourth arm useless. A tangled mess of hand flesh dangles from his wrist.",
    "s3": 0,
    "t4": "The spinning metal meteor hurtles towards Brutadon, but he does not flinch. The attack helicopter sails by his head. It does not touch him. Gromyulox is astonished by Brutadon's resolve and courage.",
    "s4": 1,
    "t5": "Brutadon throws his hands up to cover his face, cowering in fear. The spinning blades rip one of his hand to shreds, rendering his fourth arm useless. A tangled mess of hand flesh dangles from his wrist.",
    "s5": 0,
    "t6": "This is an urgent problem and Brutadon doesn't have time for your incoherent mumblings!",
    "s6": ""
  },
  {
    "prompt": "Gromyulox reaches behind his back and pulls something out. You squint through the mist to see what sort of nefarious weapon he has drawn. But no, it is an immense chess board!  He claims the white pieces and plays pawn to e4.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon plays an aggressive variation of the Sicilian dragon. He sacrifices his knight to create tempo and kingside pressure. As the complexity of the tactics mount, Gromyulox cannot keep up. Brutadon checkmates him in 29 moves. Brutadon roars his pleasure at the hard-fought victory.",
    "s1": 1,
    "t2": "Brutadon plays the Scandinavian defense, 2 d5, which he has been very pumped to try. Unfortunately, Gromyulox has prepared for these lines better than Brutadon, and Brutadon is already losing when he comes out of the opening. He is unable to gain any advantages in the midgame and he loses a pawn and king endgame. Gromyulox laughs and acid spittle flies everywhere.",
    "s2": 0,
    "t3": "Brutadon plays the opening that he is most comfortable with -- the classical main-line of the French Defense. He emerges from the opening without much of a material advantage, but he is much more comfortable with the typical motifs in the position than Gromyulox, and he traps him with a tricky 4 move tactic. Brutadon roars his pleasure at the hard-fought victory.",
    "s3": 1,
    "t4": "Brutadon plays a conservative, closed variation of the Yugoslav defense. He allows Gromyulox to take control of the center, and Gromyulox's solid positional play does not give Brutadon any openings. Gromyulox wins with the bishop in a bishop and knight endgame. Gromyulox laughs and acid spittle flies everywhere.",
    "s4": 0,
    "t5": "Without your input, Brutadon decides to play the opening that he is most comfortable with -- the classical main-line of the French Defense. He emerges from the opening without much of a material advantage, but he is much more comfortable with the typical motifs in the position than Gromyulox, and he traps him with a tricky 4 move tactic. Brutadon roars his pleasure at the hard-fought victory.",
    "s5": 1,
    "t6": "Brutadon didn't understand that. He could use your advice on the best approach to his chess game.",
    "s6": ""
  },
  {
    "prompt": "Gromyulox sweeps his tail through a nursery school! You and Brutadon can both see one small child whirl up into the air, going: <phoneme alphabet=\"ipa\" ph=\"ɑɑɑɑɑɑɑɑɑɑɑɑɑɑɑɑɑɑɑ\">aaaaaaaaahhhhhhhhhh!!!!</phoneme>",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "t1": "Wrong move, Brutadon! Brutadon whacks the child out of the sky with his claw! It vanishes in a puff of baby parts! To say this is extremely disturbing would be an understatement! You can hear the child's mother screaming below!",
    "s1": 0,
    "t2": "Brutadon flexes so hard that he sends a shockwave racing through the air toward the baby! It hits the baby and knocks it far out to sea! Nobody can tell what happens to the baby after it lands in the ocean, but at least it isn't graphically on Brutadon's conscience!",
    "s2": 0,
    "t3": "Brutadon leaps through the air, carefully catching the baby before it falls! Brutadon bends down to place the baby directly in its crying mother's arms. Amazing! His heart swells three sizes! Liquid courage fills his veins! He feels like he can accomplish anything!",
    "s3": 1,
    "t4": "Brutadon just lets the baby fall out of the sky and splatter all over the ground. To say this is extremely disturbing is an understatement! You can hear the child's mother screaming below!",
    "s4": 0,
    "t5": "Brutadon can't hear you over the piercing sound of the screaming baby!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox drops to the ground and starts doing pushups. Oh snap. It's time for a gahhddamn push up contest.",
    "wreck": 1,
    "pump": 1,
    "got": 1,
    "hold": 2,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon drops to the ground and starts doing pushups. Gromyulox must have been insane to challenge someone with 7 arms to a push up contest. He puts in an impressive effort, but Brutadon continues doing pushups long after Gromyulox has collapsed from exhaustion. Push ups are Brutadon's favorite exercise. Push ups would be your favorite exercise too if you had 7 arms.",
    "s1": 1,
    "t2": "Brutadon holds back. He does not participate in the push up contest. He mutters an unhappy growl as Gromyulox does push up after push up. Push ups are Brutadon's favorite exercise because Brutadon has 7 arms. He probably could have crushed Gromyulox in a push up contest, but instead the only thing that is crushed is Brutadon's spirit.",
    "s2": 0,
    "t3": "Taking your silence for disapproval, Brutadon does not participate in the push up contest. He mutters an unhappy growl as Gromyulox does push up after push up. Push ups are Brutadon's favorite exercise because Brutadon has 7 arms. He probably could have crushed Gromyulox in a push up contest, but instead the only thing that is crushed is Brutadon's spirit.",
    "s3": 0,
    "t4": "Brutadon didn't catch that. Gromyulox's push ups continue unchallenged.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon stomps so hard on the ground that he opens a crack in the crust of the earth! Hot lava spills out onto Main Street! People run screaming as a skyscraper topples into the rapidly-widening lava-pit!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon stomps again. This only makes the lava hole wider! He slips and falls into the lava, burning his feet! Gromyulox, however, is immune to lava! He cackles with monstrous glee!",
    "s1": 0,
    "t2": "Brutadon flexes so hard that he creates a node of superdense muscle so powerful that it has its own gravitational field! Lava comes surging out of the earth, spattering all over Gromyulox! Gromyulox isn't too badly injured, but he sure is intimidated!",
    "s2": 1,
    "t3": "Your encouragement gives Brutadon the confidence to leap straight over the lava pit and smash Gromyulox in the face! The lava pit explodes into a fireball behind him! What a stunning move! Gromyulox didn't expect Brutadon to be such a cool dude!",
    "s3": 1,
    "t4": "Brutadon stays on the far side of the lava pit. Gromyulox tries to jump across, but he falls in like a giant dweeb. Everyone on this side of the city is laughing at him, except for the people who are dead in the lava.",
    "s4": 1,
    "t5": "Brutadon freezes in confusion as the lava surrounds him. Soon his feet are trapped under rapidly-cooling rock! Gromyulox smacks him a few times with the nearest belltower. Ouch!",
    "s5": 0,
    "t6": "Brutadon can't hear you over the hiss of bubbling lava!",
    "s6": ""
  },
  {
    "prompt": "Brutadon trips and falls onto a museum of modern art! Spiky sculptures made of car fenders, air conditioning ducts, and artistic garbage stick in his skin like thorns!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 1,
    "huh": 4,
    "t1": "Brutadon crushes the entire museum! But bystanders get it all on tape. He'll have the insurance companies coming after him later, if he even survives this fight!",
    "s1": 0,
    "t2": "Brutadon flexes in the rubble, destroying the museum even further! But bystanders get it all on tape. He'll have the insurance companies coming after him later, if he even survives this fight!",
    "s2": 0,
    "t3": "Brutadon gingerly extracts himself from the rubble, avoiding destroying any more sculptures. Phew! Most of the museum is unharmed, and the city's cultural heritage is saved.",
    "s3": 1,
    "t4": "Brutadon can't hear you over the sound of the emergency alarms going off in the museum.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon accidentally steps in a dog boarding kennel! Kaijew are the natural enemies of hounds, so all the dogs begin biting and scratching him at once!",
    "wreck": 1,
    "pump": 1,
    "got": 1,
    "hold": 2,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon stomps and stomps and stomps on the dogs! The ones he kills stick to his feet like tufts of fluff. The ones who escape return to attack him with even greater ferocity! Oh no! He flees the kennel, Gromyulox hot on his tail!",
    "s1": 0,
    "t2": "Brutadon leaps out of the kennel, trying hard not to squash any doggos! Phew, close call! Brutadon is allergic to dogs!",
    "s2": 1,
    "t3": "Brutadon isn't sure how to deal with dogs! He freaks out, and the dogs climb all over his body, biting him and pooping and peeing on him! Oh no, he's breaking out in hives! Brutadon is allergic to dogs!",
    "s3": 0,
    "t4": "Brutadon can't hear you over the sound of all these barking doggos!",
    "s4": 0,
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox trips and falls into the lion pen at the zoo! There's an opening for Brutadon to make a move!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon jumps and lands on Gromyulox with all his feet at once! Gromyulox barfs up the whales he ate for dinner yesterday, which attracts a horde of lions! Brutadon laughs as Gromyulox is mauled by several dozen predatory cats!",
    "s1": 1,
    "t2": "Brutadon flexes mightily while standing over Gromyulox! Gromyulox is intimidated, and all the lions are extremely impressed! Brutadon feels like he can do anything!",
    "s2": 1,
    "t3": "Brutadon watches as a whole zoo of lions all jump on Gromyulox at once! But Gromyulox is too powerful, he smashes the lions, killing an entire pride in one blow! As he stands up, streaming with lion blood, Brutadon is very intimidated!",
    "s3": 0,
    "t4": "Brutadon just stands there and watches as a whole zoo of lions all jump on Gromyulox at once! But Gromyulox is too powerful, he smashes the lions, killing an entire pride in one blow! As he stands up, streaming with lion blood, Brutadon is very intimidated!",
    "s4": 0,
    "t5": "Brutadon cannot hear you over the roaring of all these lions!",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox trips and stumbles into the parking lot of the local football stadium, exactly five minutes after today's game has finished! Cars crash into Gromyulox, and drunk fans pelt him with beer cans! There's an opening for Brutadon to make a move!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon grabs Gromyulox by the back of the neck and smashes his face into the side of the football stadium! Gromyulox roars in pain, but thousands of fans die at once! This is gonna come back to haunt Brutadon, for sure!",
    "s1": 0,
    "t2": "Brutadon roars extremely loudly, and all the sports enthusiasts clear the area! Once they're gone, he kicks Gromyulox in one of his many groins and suplexes him down into the middle of the parking lot. Rad!",
    "s2": 1,
    "t3": "Brutadon just watches in silence as Gromyulox stomps all over the sports fans, destroying their cars and turning their bodies into paste. This makes Brutadon extremely sad!",
    "s3": 0,
    "t4": "Brutadon can't hear you over the sound of these jeering sports fans.",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox reaches behind his back, and pulls out a switchblade the size of a city bus! He dances from foot to foot and jabs it threateningly at Brutadon's throat!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 1,
    "huh": 4,
    "t1": "Brutadon rushes forward, and Gromyulox stabs him in the ribs! He stabs him several times before the blade becomes trapped between his scales! Then he retreats, while rhythmically snapping his fingers!",
    "s1": 0,
    "t2": "Brutadon flexes! This achieves nothing, and Gromyulox stabs him in the ribs! He stabs him several times before the blade becomes trapped between his scales! Then he retreats, while rhythmically snapping his fingers!",
    "s2": 0,
    "t3": "Brutadon stays back! Gromyulox starts to perform a number of fancy tricks with his switchblade, until he makes a mistake, and cuts himself on the hand, like a moron! Brutadon chuckles in glee!",
    "s3": 1,
    "t4": "Brutadon can't hear you over the snick-snick-snick sound of Gromyulox's switchblade!",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox reaches into his throat and pulls out, a rusted nuclear test device he found on the ocean floor! Holy crap!",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "t1": "Brutadon rushes forward, grabs the nuke, and dives into the sea! It explodes, killing millions of fish and injuring him gravely. He may have gigantic, oozing, nuclear, oceanic sores all over his body, but at least the city is saved!",
    "s1": 0,
    "t2": "Gromyulox flexes his gigantic muscles and swats his fist at the nuke, knocking it out over the sea! It explodes three miles away over the ocean, killing millions of fish and destroying an entire coral reef. The city is saved, though!",
    "s2": 1,
    "t3": "Brutadon watches passively as Gromyulox explodes his nuke over downtown, flattening many buildings and killing millions of people! Wow, Brutadon feels terrible!",
    "s3": 0,
    "t4": "Brutadon can't hear you over the sound of the blood pumping in his ears!",
    "s4": "",
    "t5": "",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Gromyulox grabs the side of a huge skyscraper and begins to climb it, limb over limb. Brutadon grabs on to the skyscraper and climbs right after him. Glass and steel shower the ground.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon speeds up his climb and grabs Gromyulox by one of his ankles! He pulls him from the building. Windows erupt as Gromyulox tries to hold on, but he cannot. He falls 70 stories to crunch on the ground below. Brutadon roars in triumph.",
    "s1": 1,
    "t2": "Brutadon attempts to pump it up, but flexing is flexing and climbing is climbing and never the twain shall meet. He falls 50 stories and crashes into the ground, humiliated.",
    "s2": 0,
    "t3": "Brutadon holds back, allowing Gromyulox to rush ahead of him. Upon reaching the top of the skyscraper, Gromyulox sees Brutadon far below and, with a savage grin, slides down the building like a fire pole. Pow! He crashes into Brutadon's head. Ouch town U S A.",
    "s3": 0,
    "t4": "Brutadon is lost without your help. In his confusion, he attempts to pump it up, but flexing is flexing and climbing is climbing and never the twain shall meet. He falls 50 stories and crashes into the ground, humiliated.",
    "s4": 0,
    "t5": "Brutadon didn't make that out. Try annunciating.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon and Gromyulox are underwater. You float on the surface, watching as they slowly circle one another. Fish flee, burbling, into the nearest coral structure.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon tries his best to wreck it, but his many arms drag too slowly through the water, and he cannot, in fact, wreck it. Gromyulox, on the other hand, was born in the ocean. Molded by it. He didn't see the surface until he was already a very large kaijew indeed. He kicks Brutadon so hard that one of Brutadon's lungs collapses.",
    "s1": 0,
    "t2": "Brutadon tries his best to pump it up, but his many limbs drag too slowly in the water, and he cannot, in fact, pump it up. Gromyulox, on the other hand, was born in the ocean. Molded by it. He didn't see the surface until he was already a very large kaijew indeed. He kicks Brutadon so hard that one of Brutadon's lungs collapses.",
    "s2": 0,
    "t3": "Gromyulox, coming from the ocean, is the most nimble ocean fighter, but Brutadon is the most patient. Brutadon dodges and blocks all of Gromyulox's blows, he waits for an opening, and then he takes that opening, and puts Gromyulox into a painful underwater leg triangle. Nice.",
    "s3": 1,
    "t4": "Brutadon, without your guidence, does not know how to fight underwater. Gromyulox, on the other hand, was born in the ocean. Molded by it. He didn't see the surface until he was already a very large kaijew indeed. He kicks Brutadon so hard that one of Brutadon's lungs collapses.",
    "s4": 0,
    "t5": "Brutadon can't hear you. It might be because he's underwater.",
    "s5": "",
    "t6": "",
    "s6": ""
  },
  {
    "prompt": "Brutadon and Gromyulox, thoroughly exhausted, are taking turns punching one another. Brutadon punches Gromyulox. Whammo! Gromyulox rocks back on his feet. Gromyulox rights himself and punches Brutadon. Whammo! Brutadon grunts and shakes it off, winding up his next punch.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "t1": "Brutadon nods his hefty head. He's trying to wreck it. He's trying his best. He punches Gromyulox. Whammo. Gromyulox punches back. Whammo. But this time, Brutadon is really on the ropes. Gromyulox comes in for a double whammo follow up and Brutadon slumps his shoulders. He has lost this round.",
    "s1": 0,
    "t2": "Brutadon shakes his legs. He stretches his 7 shoulders. He cracks his neck. And he flexes. He pumps it up. His reptilian muscles glisten in the sun. Energy courses back into his limbs. This time, instead of a simple whammo, he delivers a triple whammo! Gromyulox falls. Brutadon has won this round.",
    "s2": 1,
    "t3": "Brutadon shakes his legs. He stretches his 7 shoulders. He cracks his neck. He does a small amount of tai chi. He's got this. Energy courses back into his limbs. This time, instead of a simple whammo, he delivers a triple whammo! Gromyulox falls. Brutadon has won this round.",
    "s3": 1,
    "t4": "Brutadon takes a minute to hold back. He stretches his 7 shoulders. He cracks his neck. He takes a deep breath, filling his many internal and external lungs. Energy courses back into his limbs. This time, instead of a simple whammo, he delivers a triple whammo! Gromyulox falls. Brutadon has won this round.",
    "s4": 1,
    "t5": "Brutadon, absent your input, continues unabated. He punches Gromyulox. Whammo. Gromyulox punches back. Whammo. But this time, Brutadon is really on the ropes. Gromyulox comes in for a double whammo follow up and Brutadon slumps his shoulders. He has lost this round.",
    "s5": 0,
    "t6": "Brutadon didn't catch that. His head is addled from the many punches that it has received.",
    "s6": ""
  },
  {
    "prompt": "Gromyulox is trying to get away, tend to his wounds, and perhaps ready a weapon that he has secreted away in an underwater bunker. He trudges out to sea. Brutadon smashes a large chunk of freeway, forming an impromptu surfboard, and follows him.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 1,
    "none": 4,
    "huh": 5,
    "t1": "Brutadon feels that he cannot reach Gromyulox, because the waves are going towards him, and surfing doesn't work that way. Instead, he hurtles the freeway chunk like a discus. Unfortunately, he misses Gromyulox. Gromyulox reaches his secret weapon, which is a bazooka, and shoots it right between Brutadon's eyes. Owowowowowowowowow.",
    "s1": 0,
    "t2": "You have given Brutadon an idea. He pumps it up, smashing his fists into the water. Huge waves surge away from him, and he jumps onto one of them with his freeway surfboard. He catches Gromyulox and does a gnarly 1eighty shove it, smacking Gromyulox with his board. Epic. Rad. Super stoked, brolio.",
    "s2": 1,
    "t3": "Your emotional support has given Brutadon an idea. He smashes his fists into the water. Huge waves surge away from him, and he jumps onto one of them with his freeway surfboard. He catches Gromyulox and does a gnarly 1eighty shove it, smacking Gromyulox with his board. Epic. Rad. Super stoked, brolio.",
    "s3": 1,
    "t4": "Your lack of emotional support deflates Brutadon. Gromyulox reaches his secret weapon, which is a bazooka, and shoots it right between Brutadon's eyes. Owowowowowowowowow.",
    "s4": 0,
    "t5": "Brutadon didn't catch that. The ocean is a noisy mistress.",
    "s5": "",
    "t6": "",
    "s6": ""
  }
];
exports.events1 = events1;
