var events1 = [
  {
    "prompt": "A tiny person crawls up Brutadon's back.",
    "wreck": "1",
    "pump": "2",
    "got": "2",
    "hold": "2",
    "none": "3",
    "huh": "",
    "1t": "Brutadon wrecks him.",
    "1s": "1",
    "2t": "Brutadon pumps that little guy up. The little guy stomps Brutadon's eye.",
    "2s": "0",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "This guy wants you to pump him up.",
    "wreck": "2",
    "pump": "2",
    "got": "2",
    "hold": "3",
    "none": "4",
    "huh": "",
    "1t": "You pumped him up! Great!",
    "1s": "1",
    "2t": "You didn't pump it up, you suck.",
    "2s": "0",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "4",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox knocks over the city's largest bank, pinning Brutadon beneath its financial hulk. Brutadon sobs and sniffles in shame!",
    "wreck": "1",
    "pump": "2",
    "got": "3",
    "hold": "4",
    "none": "5",
    "huh": "",
    "1t": "Brutadon takes advantage of his ground-level position and bites Gromyulox in the ankle! Take that, Gromyulox!",
    "1s": "1",
    "2t": "Brutadon flexes his giant muscles, and the bank shatters into a million pieces! Gromyulox gasps in terror!",
    "2s": "1",
    "3t": "Brutadon is heartened by your encouragement-- but encouragement can't lift banks! Gromyulox stomps on his poor face!",
    "3s": "0",
    "4t": "Brutadon growls in confusion, but he obediently lies under the bank wreckage. Gromyulox stomps all over his face! Ouch!",
    "4s": "0",
    "5t": "Brutadon is so scared! He wails and roars under the bank while Gromyulox roasts him with radioactive fire!",
    "5s": "0",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox punches Brutadon so hard, one of Brutadon's extra eyeballs falls out on the ground!",
    "wreck": "1",
    "pump": "1",
    "got": "2",
    "hold": "3",
    "none": "3",
    "huh": "4",
    "1t": "Brutadon stomps on his own eyeball! He uses his remaining ones to stare Gromyulox down! It's an incredible power move, and Gromyulox is extremely intimidated!",
    "1s": "1",
    "2t": "Brutadon grits his teeth and pushes through the pain! Your encouragement is all he needs!",
    "2s": "1",
    "3t": "Brutadon recoils, and Gromyulox closes in for a second punch. KABLAMMO! He knocks out one of Brutadon's extra tongues!",
    "3s": "0",
    "4t": "Brutadon can't hear you over his howls of pain! Speak more clearly!",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon's cell phone rings in the middle of the fight! You can tell from his anxious growls that it's his tax preparer! This call is too important for him to skip!",
    "wreck": "1",
    "pump": "1",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "Brutadon roars into his cell phone, shattering it into a million pieces! Oh no! That's going to affect his maximum return!",
    "1s": "0",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Suddenly, you see the expression on Brutadon's face change. You can tell that he's experiencing a bout of imposter syndrome!",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon's spirit is burdened. It has been a difficult day, and you can see it on Brutadon's craggy face. He sits down on a nearby apartment building, despondent.",
    "wreck": "1",
    "pump": "2",
    "got": "1",
    "hold": "3",
    "none": "",
    "huh": "",
    "1t": "Brutadon had forgotten the intrinsic joy of his colossal existence. He, can wreck them. He, will wreck them. He punches a car-sized hole in the apartment building. He is filled with determination. ",
    "1s": "1",
    "2t": "Brutadon does not feel like pumping it up. Brutadon does not feel that you empathize with his existential woe.",
    "2s": "0",
    "3t": "Brutadon has held back his feelings for so long that he feels like his heart is about to pop like a bubble.",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  }
];
exports.events1 = events1;