var events1 = [
  {
    "prompt": "Gromyulox knocks over the city's largest bank, pinning Brutadon beneath its financial hulk. Brutadon sobs and sniffles in shame!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": "",
    "1t": "Brutadon takes advantage of his ground-level position and bites Gromyulox in the ankle! Take that, Gromyulox!",
    "1s": 1,
    "2t": "Brutadon flexes his giant muscles, and the bank shatters into a million pieces! Gromyulox gasps in terror!",
    "2s": 1,
    "3t": "Brutadon is heartened by your encouragement-- but encouragement can't lift banks! Gromyulox stomps on his poor face!",
    "3s": 0,
    "4t": "Brutadon growls in confusion, but he obediently lies under the bank wreckage. Gromyulox stomps all over his face! Ouch!",
    "4s": 0,
    "5t": "Brutadon is so scared! He wails and roars under the bank while Gromyulox roasts him with radioactive fire!",
    "5s": 0,
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox punches Brutadon so hard, one of Brutadon's extra eyeballs falls out on the ground!",
    "wreck": 1,
    "pump": 1,
    "got": 2,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "1t": "Brutadon stomps on his own eyeball! He uses his remaining ones to stare Gromyulox down! It's an incredible power move, and Gromyulox is extremely intimidated!",
    "1s": 1,
    "2t": "Brutadon grits his teeth and pushes through the pain! Your encouragement is all he needs!",
    "2s": 1,
    "3t": "Brutadon recoils, and Gromyulox closes in for a second punch. KABLAMMO! He knocks out one of Brutadon's extra tongues!",
    "3s": 0,
    "4t": "Brutadon can't hear you over his howls of pain! Speak more clearly!",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon's cell phone rings in the middle of the fight! You can tell from his anxious growls that it's his tax preparer! This call is too important for him to skip!",
    "wreck": 1,
    "pump": 1,
    "got": 2,
    "hold": 2,
    "none": 3,
    "huh": 4,
    "1t": "Brutadon roars into his cell phone, shattering it into a million pieces! Oh no! That's going to affect his maximum return!",
    "1s": 0,
    "2t": "Brutadon goes on the retreat, successfully sidestepping all of Gromyulox's punches! He successfully resolves the confusion about his freelance income mid-fight, which will help his tax preparer maximize his returns. Wow!",
    "2s": 1,
    "3t": "Brutadon is too confused to solve this problem without your help! He hurls his cell phone into the sea. Oh no! That's going to affect his maximum return!",
    "3s": "",
    "4t": "Brutadon can't hear you over the voice of his tax preparer! Speak more clearly!",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Suddenly, you see the expression on Brutadon's face change. You can tell that he's experiencing a bout of imposter syndrome!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon doesn't feel confident enough to wreck anyone today! He cowers in shame and Gromyulox punches him in the gut!",
    "1s": 0,
    "2t": "Brutadon halfheartedly tries to pump himself up, but he's feeling too imposterish to fully flex his muscles to their full potential. Oh no!",
    "2s": 0,
    "3t": "You are a true friend. When Brutadon feels cherished by a true friend, he can achieve anything. He shakes himself free from the metaphorical tentacles of imposter syndrome, and faces the actual tentacles of Gromyulox's horrible monster body!",
    "3s": 1,
    "4t": "Brutadon's already holding back. He's been holding himself back in fear this whole time. When he hears your voice, a single steaming tear rolls down his scaly cheek, and he knows that he's an imposter, just like he always feared.",
    "4s": 0,
    "5t": "Brutadon waits and waits for emotional support from you during this time of need, but it never comes. A single steaming tear rolls down his scaly cheek, and he knows that he's an imposter, just like he always feared.",
    "5s": 0,
    "6t": "Brutadon can't hear you over the sound of his churning, imposter thoughts. Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox trips on a firetruck, opening himself up for a strike!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon ducks low and swings hard, smashing Gromyulox in the ribs! Success! Gromyulox roars in all seven of his cosmic pain languages!",
    "1s": 1,
    "2t": "Brutadon flexes impressively! It's cool, but unfortunately it has no effect on Gromyulox's health or wellbeing!",
    "2s": 0,
    "3t": "Brutadon sees the opening, but he doesn't strike! Gromyulox uses this opportunity to regain his monstrous strength. Every inch of his hide starts to ooze radioactive nitro-sweat. Now he's even more dangerous!",
    "3s": 0,
    "4t": "Without your guidance, Brutadon just does what he's most comfortable with: helpless flailing and stomping! None of his hits connectl. Gromyulox cackles in glee!",
    "4s": 0,
    "5t": "Brutadon can't hear you over the sound of Gromyulox's shrieking! Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon and Gromyulox stumble into the middle of a wedding! Guests run screaming in every direction!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon crushes hundreds of wedding guests with his enormous toes! Dresses and tuxedoes wet with blood cling to the soles of his feet!",
    "1s": 0,
    "2t": "Brutadon flexes and expands his neck sacs and howls at the sky! Every glass in the reception shatters, but at least nobody got hurt!",
    "2s": 1,
    "3t": "Brutadon's eyes light up. You got this, Brutadon? Does that mean this wedding cake is for him? He reaches down, scoops up the entire buffet, and swallows it whole-- along with half the wedding party! Oh no!",
    "3s": 0,
    "4t": "Brutadon balances on one foot as helpless wedding guests scramble to get out of the way. Gracefully, he avoids hurting even one person!",
    "4s": 1,
    "5t": "Brutadon panics and freaks out and just crushes the entire wedding! Poor guy! He probably could have used some guidance there!",
    "5s": 0,
    "6t": "Brutadon can't year you over the sound of the wedding band! Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox bites down hard on Brutadon's bicep! Brutadon wails in pain!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon tries to wreck him, but he can't! His punching arm is trapped in Gromyulox's diamond teeth! His sizzling hot blood splatters everywhere!",
    "1s": 0,
    "2t": "Brutadon flexes so hard, he shatters every one of Gromyulox's diamond teeth! Tooth shards glitter in the sun! Wow!",
    "2s": 1,
    "3t": "Brutadon is terrified. He doesn't got this! Gromyulox has got this, if by \"this\" we mean \"Brutadon's arm\"! Gromyulox uses this opportunity to punch Brutadon in the neck!",
    "3s": 0,
    "4t": "Brutadon follows your orders, and just lets Gromyulox bite the hell out of his poor arm! Ouch! Brutadon's steaming blood flies sizzling through the sky!",
    "4s": 0,
    "5t": "Brutadon doesn't know what to do! He just stands there and lets Gromyulox chew all over his poor arm! Ouch! He howls miserably at the sky!",
    "5s": 0,
    "6t": "Brutadon can't hear you over the sound of his muscles getting all chewed up! Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox and Brutadon trip over a bridge and fall into the river with a splash. Gromyulox tries to push Brutadon's head underwater!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon obeys your orders and wrecks the bridge. It falls on him and trap him in the river! He inhales fifty million gallons of water, extinguishing three of his five radioactive lungs! Oh no!",
    "1s": 0,
    "2t": "Brutadon sucks up a mouthful of water and spits it at Gromyulox! it's boiling hot! Gromyulox's outer skin melts and sluffs off in sheets of sizzling meat! The crowd on the riverbank cheers!",
    "2s": 1,
    "3t": "Brutadon steels his resolve and holds his breath underwater! Gromyulox thinks he has won. But then Brutadon rears up out of the river and socks Gromyulox in the jaw! Good one Brutadon!",
    "3s": 1,
    "4t": "Brutadon freaks out and struggles! But the more he struggles, the more water he swallows! He inhales fifty million gallons of river, extinguishing three of his five radioactive lungs! Oh no!",
    "4s": 0,
    "5t": "Brutadon can't hear you over the water churning in his ears! Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon's spirit is burdened. It has been a difficult day, and you can see it on Brutadon's craggy face. He sits down on a nearby apartment building, despondent.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon had forgotten the intrinsic joy of his colossal existence. He, can wreck them. He, will wreck them. He punches a car-sized hole in the apartment building. He is filled with determination.",
    "1s": 1,
    "2t": "Brutadon does not feel like pumping it up. Brutadon does not feel that you empathize with his existential woe.",
    "2s": 0,
    "3t": "Brutadon has held back his feelings for so long that he feels like his heart is about to pop like a bubble.",
    "3s": 0,
    "4t": "You ignore Brutadon, just like he has been ignoring his innermost turmoil for his entire life.",
    "4s": 0,
    "5t": "Brutadon growls in sad confusion. He can't tell what you said.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox roars and nearby windows shatter. Although Brutadon knows that he is a bad customer, he is afraid that Gromyulox is even badder.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon roars right back at Gromyulox. His cheeks quiver with sonic fury. Gromyulox recoils from the noise, like a coward. Brutadon has won this round.",
    "1s": 1,
    "2t": "Brutadon flexes his muscles. Although he knows that they are large, he cannot help but look over at Gromyulox's seven massive biceps, which are extremely intimidating.",
    "2s": 0,
    "3t": "In the face of doubt, Brutadon holds fast. He knows that he is very large and very strong. This is not a David and Goliath situation. It is a Goliath and Goliath situation. Brutadon roars wtih confidence.",
    "3s": 1,
    "4t": "Without your encouragement, Brutadon's doubt festers like a wound in his brain. A wound that is becoming infected. Brutadon flinches. Gromyulon has won this round of psychic battle.",
    "4s": 0,
    "5t": "Brutadon doesn't know what you're saying. He continues to feel unsure about his badditude.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox swings his giant fist. Brutadon ducks to the side like a hefty, thumping ninja. He looks over at you, face plastered with a reptilian smile.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon simultaniously jabs from the left, jabs from the right, and uses his middle arm to uppercut Gromyulox's largest chin. Gromyulox gets wrecked. He gets wrecked real good.",
    "1s": 1,
    "2t": "Brutadon pumps up his muscles. Gromyulox is surprised, perhaps even slightly cowed, by the combination of Brutadon's dexterity and muscularity.",
    "2s": 1,
    "3t": "Brutadon holds back and he misses his opening. His lizardish smile turns to a lizardish frown when Gromyulox's follow up combination strikes him right in his topmost liver.",
    "3s": 0,
    "4t": "Brutadon was waiting for your encouragement, but he did not get it. Gromyulox takes advantage of Brutadon's hesitation with a spinning triple kick. Brutadon crashes to the ground, killing one hapless human and causing several others to suffer from years of P T S D.",
    "4s": 0,
    "5t": "Brutadon did not understand you. He continues to grin, waiting for you to clarify your instructions.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon showers Gromyulox with a barrage of flying hammer punches, but Gromyulox blocks all of them. Brutadon grunts in frustration. He is not sure if he's got this.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 1,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon continues to hammer punch, even though Gromyulox has clearly mastered the art of blocking hammer punches. Brutadon tires himself out. The spikes on the bottom of Gromyulox's feet emerge from their gooey pouches, and Gromyulox stomps on Brutadon's feet.",
    "1s": 0,
    "2t": "Hammer punches clearly are not working. Brutadon shifts to a different tactic -- the tried and true flexing that he has practiced during your training sessions for hundreds of hours. Unfortunately, flexing is not the correct move in this situation, and Brutadon gets 3 of his 700 teeth knocked out.",
    "2s": 0,
    "3t": "Yes. He, does, got this. He switches from hammer punches to asteroid elbows, and one of them lands on Gromyulox's fleshy left neck, causing the concrete below your feet to crackle like a space blanket.",
    "3s": 1,
    "4t": "Without your input, Brutadon continues to hammer punch, even though Gromyulox has clearly mastered the art of blocking hammer punches. Brutadon tires himself out. The spikes on the bottom of Gromyulox's feet emerge from their gooey pouches, and Gromyulox stomps on Brutadon's feet.",
    "4s": 0,
    "5t": "Brutadon doesn't understand you, perhaps because the thunder of the hammer punches is pretty loud.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "You notice that standing next to Brutadon's left foot, a brave spectator is trying to take a selfie with Brutadon.",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon smooshes that spectator with a casual stomp. This will be a P R disaster.",
    "1s": 0,
    "2t": "Brutadon strikes a heroic pose for the spectator. You know that this will bolster Brutaon's viral presence on social media.",
    "2s": 1,
    "3t": "Brutadon avoids squashing the spectator and maintains his focus on the fight with Gromyulox. The selfie that the spectator took will later go viral and be featured on Good Morning America.",
    "3s": 1,
    "4t": "Brutadon does not notice the spectator and he accidentally crushes half of the spectator's body under his right toe. The spectator still manages to take a selfie, but the selfie is the stuff of nightmares. This will be a P R disaster.",
    "4s": 0,
    "5t": "Brutadon knows that you are trying to say something, but he didn't hear you very well. The situation continues to be very dangerous for the spectator.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon spins like a tornado and his spikey tail whistles through the air. It is a truly terrifying sight. Gromyulox cannot get away in time. Globules of blood, the color of Merlot, slop onto the concrete.",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "1t": "Oh, he wrecked it. Damn straight did he wreck it. Your enthusiasum is contagious. Brutadon's emotion bulb turns a pleasing shade of orange and you know this means that he feels like he can take on the world.",
    "1s": 1,
    "2t": "Damn straight. Your enthusiasum is contagious. Brutadon's emotion bulb turns a pleasing shade of orange and you know this means that he feels like he can take on the world.",
    "2s": 1,
    "3t": "Brutadon does not maintain his elevated hype level and he exits his state of flow. Sometimes, if you do not celebrate your victories, they do not sink in.",
    "3s": 0,
    "4t": "Brutadon didn't understand you. You should probably encourage Brutadon because that was pretty bad ass.",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon steps on a statue of a Civil War general, and the statue's stone sword sticks in his toe like a splinter! Ouch!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon roars in anger and smashes the statue into a million tiny pieces! It makes him feel a lot better! He pushes through the pain!",
    "1s": 1,
    "2t": "Brutadon flexes his toe muscles so hard, that the splinter shoots out of his toe like a missile, and hits Gromyulox dead in the eyeball! Hell yeah!",
    "2s": 1,
    "3t": "Brutadon grits his teeth and pushes through the pain! Splinters mean nothing! Toes mean nothing! Toes are like dirt! Brutadon roars at the sky and slaps Gromyulox across the face!",
    "3s": 1,
    "4t": "Brutadon favors his injured foot. Gromyulox notices this weakness! He closes in and lands a flurry of bone, destroying, punches, on Brutadon's vulnerable side!",
    "4s": 0,
    "5t": "Brutadon tries to muddle through the pain, but Gromyulox notices his injury! He stomps down, hard, on Brutadon's toe. Brutadon's scream of pain shatters all the windows on the west side of town!",
    "5s": 0,
    "6t": "Brutadon can't hear you over the sound of his own sniffles. Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Brutadon smells a delicious panini, cooking in a nearby restaurant! Oh no! It's distracting him!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon smashes the restaurant! All the people and objects inside it, are crushed and mixed together into a paste! They will have to be buried with their paninis!",
    "1s": 0,
    "2t": "Brutadon flexes so hard, that his muscles release a cloud of battle pheromones! This scent blocks out the alluring smell of the paninis. Brutadon is saved!",
    "2s": 1,
    "3t": "Brutadon takes your advice, and goes to find these delicious paninis. Gromyulox uses this opportunity to stab Brutadon in the butt with one of his venom tusks! Brutadon roars in agony!",
    "3s": 0,
    "4t": "Brutadon successfully restrains himself! Now is the time for deadly battle, not for paninis!",
    "4s": 1,
    "5t": "Without anyone to tell him it's a bad idea, Brutadon goes to find these delicious paninis. Gromyulox uses this opportunity to stab Brutadon in the butt with one of his venom tusks! Brutadon roars in agony!",
    "5s": 0,
    "6t": "Brutadon can't hear you over the chorus of  his subconscious as it demands paninis. Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox rips up a railroad and cracks it through the air like a whip. Oh no! It's electrified, and very dangerous!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon rushes forward. Bad idea! He gets electrical burns, all over his precious neon hide!",
    "1s": 0,
    "2t": "Brutadon starts showing off all his muscles. But while he's grunting, and flexing, Gromyulox slashes him with the electrical railroad. YAOWCH! That hurts!",
    "2s": 0,
    "3t": "Brutadon gets out of range of Gromyulox's electrical railroad whip. Good idea! Gromyulox just ends up tangling himself in his own weapon, and giving himself electrical burns, on all twelve of his thighs!",
    "3s": 1,
    "4t": "Brutadon isn't sure what to do, so he just flops down on the ground, and cries, while Gromyulox hits him with the electrical railroad. YAOWCH!",
    "4s": 0,
    "5t": "Brutadon can't hear you over the sound of the crackling electrical railroad whip. Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox grabs a cell phone tower, and hurls it at Brutadon like a spear!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon smashes the cellphone tower out of the air, with one swipe of his gigantic claw! It sticks in a nearby hill like an arrow. Awesome! People all over the east side of town gasp in amazement!",
    "1s": 1,
    "2t": "Brutadon flexes so hard that his outer scales transform suddenly into diamond! The cellphone tower bounces harmlessly off his impenetrable hide!",
    "2s": 1,
    "3t": "Brutadon steels his nerves. At the last moment, he expertly sidesteps the cellphone tower! It buries itself in the ground exactly where he was standing, and explodes in a giant fireball for some reason! Close call!",
    "3s": 1,
    "4t": "Brutadon retreats out of the range of Gromyulox's puny throw. Hah! What a bad thrower! Gromyulox must not have a cool friend to play football with him in the park, like Brutadon does.",
    "4s": 1,
    "5t": "Brutadon isn't sure what to do, so he hesitates. Wrong decision! The cellphone tower spears him in the side! Sizzling blood globs spray everywhere!",
    "5s": 0,
    "6t": "Brutadon can't hear you over the sound of the deadly cell phone tower whistling through the air! Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox grabs a school bus full of children and swings it at Brutadon like a club!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 1,
    "huh": 5,
    "1t": "Brutadon rushes forward, and the bus connects hard with the side of his head! Splattered, schoolchildren, stream down his face in chunks! Brutadon is dazed by both the pain and the horror!",
    "1s": 0,
    "2t": "Brutadon stands aside and flexes all of his limbs simultaneously. Inside the schoolbus, the children catch a glimpse of his glorious muscles, and the terror in their hearts is calmed. As Gromyulox hurls them into the river, they die in peace. Good job Brutadon!",
    "2s": 1,
    "3t": "Brutadon deftly catches the schoolbus and rips it out of Gromyulox's claws. He sets it down carefully on the road. Most of the children survive! Good job Brutadon!",
    "3s": 1,
    "4t": "Brutadon jumps back, and dodges the swing. Inside the schoolbus, the children catch a glimpse of his glorious muscles rippling past the windows, and the terror in their hearts is calmed. As Gromyulox hurls them into the river, they die in peace. Good job Brutadon!",
    "4s": 1,
    "5t": "Brutadon can't hear you over the sound of the screaming schoolchildren! Speak more clearly.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox hipchecks Brutadon into the largest skyscraper downtown and bodyslams him into the park! Brutadon is dazed and half-buried by rubble!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon grabs Gromyulox by the ankle and hurls him into the duck pond! Gromyulox wails in horror as enormous hives sprout all over his three butts. His kind is allergic to waterfowl!",
    "1s": 1,
    "2t": "Brutadon flexes so hard that the lumps of rubble and debris bounce off his hide and fly through the air like missiles! Every window nearby is shattered, and Gromyulox staggers backward across midtown! Nice!",
    "2s": 1,
    "3t": "Brutadon tries to smile, while Gromyulox pummels him in the face. Ouch! Ouch! Ouch! Smiling doesn't help!",
    "3s": 0,
    "4t": "Brutadon lies flat on the ground in the park while Gromyulox sits on his back and bites his neck. This is not a winning strategy!",
    "4s": 0,
    "5t": "Brutadon can't hear you over the sound of the ducks freaking out in the duck pond. Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon stands over Gromyulox, punching him again and again in the face. But an airplane is coming in for a landing at the city airport, and Brutadon's head is right in the way!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 2,
    "huh": 5,
    "1t": "At exactly the right moment, Brutadon bends over to bite Gromyulox in the neck, and the airplane just misses his shoulders by a few feet! Wow! Close call! Everyone in the airplane is probably pooping their pants!",
    "1s": 1,
    "2t": "The plane smashes into the back of Brutadon's head, killing hundreds and burning Brutadon terribly. But at least his fine body was flexing while it happened!",
    "2s": 0,
    "3t": "Brutadon misinterprets your cheer as encouragement to keep punching! The plane smashes into the back of his head, knocking him flat! YAOWCH!",
    "3s": 0,
    "4t": "At the last second, Brutadon steps back, and the plain whizzes right through where he was standing! Close call! Everyone in the airplane is probably pooping their pants!",
    "4s": 1,
    "5t": "Brutadon can't hear you over the sound of his fists hitting Gromyulox's body! Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon and Gromyulox stumble into the middle of an illegal street race! High-powered customized cars, covered in knives and driven by howling wasteland rabble, zoom straight at their toes!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon destroys the zooming cars with a single stomp-- but huge knives and bits of twisted rebar stick in his foot! YAOWCH!! Skinhead warboy street racers are smeared all over his toes!",
    "1s": 0,
    "2t": "Brutadon roars at the cars! The force of his breath is strong enough to send them skidding back down the road! The street racers crap their pants, bail out, and run away. Nice!",
    "2s": 1,
    "3t": "Brutadon jumps back out of the cars' way. They plow into Gromyulox's ankles, and he bellows in agony! Nice!",
    "3s": 1,
    "4t": "The cars smash into Brutadon's ankles! Wasteland knives, and twisted bits of re-bar, and splinters of car metal stab him! YAOWCH!",
    "4s": 0,
    "5t": "Brutadon can't hear you over the sound of the car engines! Speak more clearly!",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "It is beginning to rain. You can tell from Brutadon's timid growl that he is remembering that one time during training that he slipped in the rain and sprained his ankle.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": 5,
    "1t": "Brutadon charges at Gromyulox, but he once again slips in the rain. That's not good. Gromyulox takes the opening. He body slams Brutadon. Ouch town.",
    "1s": 0,
    "2t": "While pumping it up, Brutadon remembers how nice you were during his recovery period from his sprained ankle. You brought him his favorite soup every day. He knows that you've got his back, and that means all the world.",
    "2s": 1,
    "3t": "As he sees you cheering him on, Brutadon remembers how nice you were during his recovery period from his sprained ankle. You brought him his favorite soup every day. He knows that you've got his back, and that means all the world.",
    "3s": 1,
    "4t": "Brutadon stews in his bad memory of the rain. In his mind, the rain is his enemy. This makes him forget about his real enemy, Gromyulox. Gromyulox kicks him in his shins and it hurts a bunch.",
    "4s": 0,
    "5t": "Brutadon can't hear you. The rain is getting pretty loud. Splish splash. You will have to talk more clearly.",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Suddenly, huge fleshy wings, drop from Gromyulox's forearms. Oh no. You didn't know that Gromyulox had wings. You haven't trained for this. Gromyulox must have hidden his wings for all of this time, waiting for the perfect moment to unfurl them.",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 4,
    "huh": "",
    "1t": "Brutadon punts a car and it flies through the air with uncanny accuracy. It tears right through Gromyulox's secret wings, rendering them flappy and unflightworthy. Nice one, Brutadon!",
    "1s": 1,
    "2t": "Brutadon flexes, trying to see if there is some hidden muscle that will reveal his own hidden wings. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "2s": 0,
    "3t": "Brutadon is dumbfounded by Gromyulox's secret wings. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "3s": 0,
    "4t": "Brutadon is dumbfounded by Gromyulox's secret wings, just like you are, apparently. Gromyulox flies high into the air, he comes plummeting down at unbearable speed, and when he crashes into Brutadon, he leaves a crater the size of a small park.",
    "4s": 0,
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Gromyulox crouches down to the ground. His body starts to get redder and redder. It seems like he is charging up some sort of super move.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon runs at Gromyulox, knocking him over before he can finish charging his super move. Gromyulox is dazed. Brutadon seizes his opening and stomps on Gromyulox with the force of ten thousand dump trucks. Damn, son.",
    "1s": 1,
    "2t": "Brutadon tries to charge up his own super move, but it is too late! A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "2s": 0,
    "3t": "Unfortunately, Brutadon don't got this. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "3s": 0,
    "4t": "Brutadon holds back, but this only allows Gromyulox to finish charging his super move. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "4s": 0,
    "5t": "While Brutadon is waiting for you to say something, Gromyulox finishes charging his super move. A huge flesh nozzle emerges from the top of Gromyulox's head and molten lava rockets through the air. Brutadon tries to dodge it but it still hits him in his back and burns it up real good. That will probably leave some gnarly scars.",
    "5s": 0,
    "6t": "Brutadon doesn't understand what you're saying. You should probably clarify soon, because Gromyulox is almost the shade of a tomato.",
    "6s": ""
  },
  {
    "prompt": "Brutadon growls, and you can tell that he has just remembered that he has to go to the post office. Going to the post office is a real chore, and it could have been avoided if Brutadon had signed up for stamps dot com. With stamps dot com you can buy and print real U S postage from the comfort of your own home. Stamps dot com makes sending packages easy. Check out stamps dot com for a no risk trial and a free postage offer! All you need to do is go to stamps dot com, click on the microphone on the top of the page, and enter, Brutadon. Why wait in long post office lines? Try stamps dot com today.",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 4,
    "huh": "",
    "1t": "Brutadon wrecks his trips to the post office by going to stamps dot com, clicking on the microphone on the top of the page, and entering, Brutadon. Nice job, Brutadon!",
    "1s": 1,
    "2t": "Brutadon is pumped up to end his trips to the post office, which are the worst part of his week. He celebrates by going to stamps dot com, clicking on the microphone on the top of the page, and entering, Brutadon. Nice job, Brutadon!",
    "2s": 1,
    "3t": "Brutadon knows what he has to do. He goes to stamps dot com, clicks on the microphone on the top of the page, and enters, Brutadon. Nice job, Brutadon!",
    "3s": 1,
    "4t": "Although Brutadon intends to sign up for stamps dot com, he does not act now. Instead, he makes a trip to the post office and has to wait in a long line. Next time, Brutadon should go to stamps dot com, click on the microphone on the top of the page, and enter, Brutadon.",
    "4s": 0,
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon opens his mouth to breathe poison gas at Gromyulox. But a cloud of Canada Geese fly straight down his throat! Oh no! He can't breathe!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "1t": "Brutadon belches fire, roasting all the geese! He swallows their crispy little bodies, and they fuel his fight energy! Get wrecked, geese!",
    "1s": 1,
    "2t": "Brutadon tries to flex, but he can't breathe! He coughs up mangled goose parts while Gronyulox punches him over and over in the neck! Ouch!",
    "2s": 0,
    "3t": "Brutadon just sits there and lets himself suffocate on a throatful of geese. Meanwhile, Gromyulox hits him over and over again, until he wobbles back and forth like a gym punching dummy. Good strategy! I mean, not a good strategy. This is sarcastic.",
    "3s": 0,
    "4t": "Brutadon can't hear you over the sound of the geese cawing in his throat. Speak more clearly!",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon stumbles into a playground! Children run screaming everywhere!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon doesn't want to, but he takes your advice and eats all the children. He belches guiltily.",
    "1s": 0,
    "2t": "Brutadon flexes for the crowd. The children are reassured by his gentle strength. They cheer!",
    "2s": 1,
    "3t": "You've assured Brutadon that these children pose him no threat. He's relieved!",
    "3s": 1,
    "4t": "Brutadon successfully avoids murdering any of the puny fleeing children with his giant feet. Good job, Brutadon.",
    "4s": 1,
    "5t": "Without your guidance, Brutadon falls to the ground in confusion, crushing several children!",
    "5s": 0,
    "6t": "Brutadon can't understand you! He balances on one foot as children scurry like ants beneath him!",
    "6s": ""
  },
  {
    "prompt": "Gromyulox charges at Brutadon with his shoulder needles set to full bristle!",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 3,
    "none": 4,
    "huh": "",
    "1t": "Brutadon lifts his fists to wreck Gromyulox, but he cannot withstand the force of Gromyulox's mighty charge! His fists are punctured with poisonous quills. Fortunately, Brutadon is impervious to poison, but the needles still hurt a bunch.",
    "1s": 0,
    "2t": "Brutadon pumps up his inflatable shield pouch, but it is a bad defense against a needled attack. The shield pouch is punctured in 30 places, rendering it flaccid and useless!",
    "2s": 0,
    "3t": "Brutadon steels himself against Gromyulox's mighty charge. He waits for his moment, and then he adroitly dodges to the side! Gromyulox collides into a power plant and he is filled with 95,000 volts of electricity! He stumbles to his feet, smoking and concussed.",
    "3s": 1,
    "4t": "Brutadon does nothing, and Gromyulox collides with him, filling his body with poisonus quills! Fortunately, Brutadon is impervious to poison, but the needles still cause him tremendous pain.",
    "4s": 0,
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon suddenly freezes. Oh no. It's happened again. He's forgotten how to punch things!",
    "wreck": 1,
    "pump": 2,
    "got": 1,
    "hold": 3,
    "none": 3,
    "huh": 4,
    "1t": "Your voice stirrs something deep inside Brutadon. He remembers: punching is about wrecking things. Punching is about destruction! He leaps on Gromyulox with renewed vigor and expresses the true platonic ideal of the punch!",
    "1s": 1,
    "2t": "Brutadon raises his fist and makes a timid pumping motion. Is this it? Is this a punch? While he's still wondering, Gromyulox decks him in the jaw. Oh, that's it. That's a punch.",
    "2s": 0,
    "3t": "Brutadon just stands there, waving his arms around, hoping that maybe he is punching. While he's still wondering, Gromyulox decks him in the jaw. Oh, that's it. That's a punch.",
    "3s": 0,
    "4t": "Brutadon can't hear you over the sound of his confused and terrified punch thoughts. Speak more clearly!",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "In the midst of furious battle, Brutadon begins to execute an extremely difficult and complex combination that he has practiced over 2000 times. You sense that this time, Brutadon is in the zone, and maybe you shouldn't distract him.",
    "wreck": 1,
    "pump": 1,
    "got": 1,
    "hold": 1,
    "none": 2,
    "huh": "",
    "1t": "Your cries of support, although well intentioned, shatter Brutadon's focus. He whiffs his seventh middle backpunch and tumbles mightily to the ground.",
    "1s": 0,
    "2t": "You silently punch the air in time with Brutadon's complex combination, and your heart swells with pride as his final triple suplex lands perfectly. Great job, Brutadon!",
    "2s": 1,
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  }
];
exports.events1 = events1;