var tutorial = [
  {
    "prompt": "Welcome to, You Got This Brutadon, a game where you must use your voice in the name of true friendship. Make sure Alexa can hear you clearly, and make sure no one will be disturbed by your cacophonous shouting.",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "If this is your first time playing, You Got This Brutadon, shout, PUMP IT UP BRUTADON, to begin the tutorial. If you would like to skip the tutorial, shout WRECK um BRUTADON.",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "We begin long ago, in middle school, when you and Brutadon first became fast friends. Brutadon was the only kaijew in your sixth grade class, and he towered seven stories above all the other students. When they made fun of him, you used to shout, wreckum, Brutadon!",
    "wreck": 1,
    "pump": 2,
    "got": 2,
    "hold": 2,
    "none": 2,
    "huh": 2,
    "1t": "After Brutadon had killed twenty-five of your classmates, no one ever made fun of him again. He learned that you were the only one who truly had his back.",
    "1s": "",
    "2t": "When your classmates made fun of Brutadon, you used to shout, wreckum, Brutadon!",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Your friendship continued into adulthood. You became a personal trainer, and Brutadon came to rely on your coaching and support. Whenever he was training for the big kaijew fight that he knew was his destiny, you would shout, pump it up Brutadon!",
    "wreck": 2,
    "pump": 1,
    "got": 2,
    "hold": 2,
    "none": 2,
    "huh": 2,
    "1t": "Brutadon pumped it up indeed. Soon, his seven biceps were each bigger than cement trucks, and his glutes thundered across the plains.",
    "1s": "",
    "2t": "Whenever Brutadon was training for the big kaijew fight that he knew was his destiny, you would shout, pump it up Brutadon!",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "But his training didn't always go perfectly. Sometimes, Brutadon worried about whether he was really strong enough to meet his fate. Whenever he was feeling down, you'd tell him, you got this, Brutadon!",
    "wreck": 2,
    "pump": 2,
    "got": 1,
    "hold": 2,
    "none": 2,
    "huh": 2,
    "1t": "With your emotional support, Brutadon could achieve anything. Before long, the whole world knew of Brutadon's strength, and he was very popular on social media.",
    "1s": "",
    "2t": "Whenever Brutadon was feeling down, you would tell him, you got this, Brutadon!",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Journalists and youtubers often made the trek to the airplane hanger in the middle of the desert where you and Brutadon trained for the big fight. Brutadon hated the press. When he got antsy about all those visitors, you'd urge him not to stomp on anybody. You said, hold back, Brutadon!",
    "wreck": 2,
    "pump": 2,
    "got": 2,
    "hold": 1,
    "none": 2,
    "huh": 2,
    "1t": "You and Brutadon were a good team. Brutadon didn't always make the best decisions on his own. He relied on you to channel his raw strength into action.",
    "1s": "",
    "2t": "You always told Brutadon not to stomp on anybody. You said, hold back, Brutadon!",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "But one day, the Pacific ocean churned, and from the dark and mysterious depths, emerged Gromyulox, a kaijew terror even bigger and badder than Brutadon. It cut a swath of destruction across Seattle, Redmond, Kirkland, and Bellview, Washington. When you and Brutadon arrived at the scene, it was a sober moment for both of you. You stood in silence and looked at the destruction.",
    "wreck": 2,
    "pump": 2,
    "got": 2,
    "hold": 2,
    "none": 1,
    "huh": 2,
    "1t": "You and Brutadon locked eyes. You both knew that this was what you had been training for. His destiny, had arrived.",
    "1s": "",
    "2t": "You stood in silence and looked at the destruction.",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Brutadon followed in Gromyulox's wake of destruction. Soon, the two stood face to face in the skyscraper-filled city of Franklin. Everyone held their breath as the two kaijew prepared to battle. But you knew that Brutadon needed your help to win. Suddenly, Gromyulox leaped forward with his poison fangs bared! Brutadon froze! Should he wreck it? Should he pump it up? Did he need to hear, you got this, Brutadon? Did he need to hold back?",
    "wreck": 1,
    "pump": 2,
    "got": 3,
    "hold": 4,
    "none": 5,
    "huh": 6,
    "1t": "Brutadon rushes forward with his teeth bared, too! His fangs clank off of Gromyulox's fangs! They each retreat. This will be a difficult fight.",
    "1s": "",
    "2t": "Brutadon flexes, and Gromyulox is shocked by both the quantity and quality of his gigantic muscles. He freezes in place, suddenly aware that this will be a very, difficult, fight.",
    "2s": "",
    "3t": "You know that Brutadon can't do this without your emotional support. He hears your cheer, and is filled with courage! He karate-chops Gromyulox in the neck with one of his giant claws. Gromyulox is stunned. Brutadon will be a much more difficult foe than he expected",
    "3s": "",
    "4t": "Brutadon dodges backward, and Gromyulox misses him by a mile! A literal mile. He plows into the river. Gromyulox suddenly realizes that this will be a very, difficult, fight.",
    "4s": "",
    "5t": "Without your support, Brutadon is overcome by self-doubt. He hesitates, and Gromyulox bites him in the neck! YAOWCH! Gromyulox roars in glee! Perhaps this battle will be easier than he thought!",
    "5s": "",
    "6t": "Brutadon can't hear you over the sounds of Gromyulox's roars! Speak more clearly!",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "Timeskip to the fight. Test event where the player needs to say the right thing out of several options",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  },
  {
    "prompt": "However many of these we need to do",
    "wreck": "",
    "pump": "",
    "got": "",
    "hold": "",
    "none": "",
    "huh": "",
    "1t": "",
    "1s": "",
    "2t": "",
    "2s": "",
    "3t": "",
    "3s": "",
    "4t": "",
    "4s": "",
    "5t": "",
    "5s": "",
    "6t": "",
    "6s": ""
  }
];
exports.tutorial = tutorial;